/**
 * PDF Export Service
 * Generates professional clinical reports as PDF
 * Uses html2pdf library (lightweight, no dependencies)
 */

export class PDFExportService {
  /**
   * Generate clinical case report as PDF
   */
  static async generateCaseReport(caseData, language = 'en') {
    const texts = {
      en: {
        title: 'SUDERM - CLINICAL CASE REPORT',
        reportDate: 'Report Date',
        patientId: 'Patient ID',
        caseId: 'Case ID',
        lesionLocation: 'Lesion Location',
        aiPrediction: 'AI Prediction',
        confidence: 'Confidence',
        doctorAssessment: 'Doctor Assessment',
        clinicalNotes: 'Clinical Notes',
        followUp: 'Follow-up Scheduled',
        tags: 'Case Tags',
        allClassPredictions: 'All Class Predictions',
        class: 'Classification',
        probability: 'Probability',
        disclaimer: 'Medical Disclaimer',
        disclaimerText: 'This report is generated by an AI diagnostic tool and should not be considered a definitive diagnosis. All findings must be reviewed and confirmed by a qualified medical professional. This tool is intended to assist clinicians in their diagnostic process, not replace clinical judgment.',
        footer: 'Generated by SUDerm - Skin Lesion Analysis System',
      },
      tr: {
        title: 'SUDERM - KLİNİK VAKA RAPORU',
        reportDate: 'Rapor Tarihi',
        patientId: 'Hasta Kimliği',
        caseId: 'Vaka Kimliği',
        lesionLocation: 'Lezyon Konumu',
        aiPrediction: 'AI Tahmini',
        confidence: 'Güven',
        doctorAssessment: 'Doktor Değerlendirmesi',
        clinicalNotes: 'Klinik Notlar',
        followUp: 'Planlanan Takip',
        tags: 'Vaka Etiketleri',
        allClassPredictions: 'Tüm Sınıf Tahminleri',
        class: 'Sınıflandırma',
        probability: 'Olasılık',
        disclaimer: 'Tıbbi Sorumluluk Reddi',
        disclaimerText: 'Bu rapor bir yapay zeka tanı aracı tarafından oluşturulmuştur ve kesin bir teşhis olarak kabul edilmemelidir. Tüm bulgular nitelikli bir tıbbi uzman tarafından gözden geçirilmeli ve doğrulanmalıdır. Bu araç, klinisyenlerin tanı sürecine yardımcı olmak için tasarlanmıştır, klinik yargıyı değiştirmez.',
        footer: 'SUDerm - Cilt Lezyonu Analiz Sistemi tarafından oluşturulmuştur',
      },
    };

    const t = texts[language] || texts.en;

    try {
      // Create HTML content
      const htmlContent = this._generateHTML(caseData, t);

      // Create temporary container
      const element = document.createElement('div');
      element.innerHTML = htmlContent;
      element.style.padding = '20px';
      element.style.fontFamily = 'Arial, sans-serif';
      element.style.maxWidth = '900px';

      // Generate PDF using html2canvas + jspdf or fallback to simple method
      await this._exportToPDF(element, `SUDerm_Report_${caseData.id || 'Export'}.pdf`);

      return true;
    } catch (error) {
      console.error('Error generating PDF:', error);
      throw new Error('Failed to generate PDF report');
    }
  }

  /**
   * Generate HTML content for the report
   */
  static _generateHTML(caseData, t) {
    const formatDate = (dateString) => {
      if (!dateString) return 'N/A';
      return new Date(dateString).toLocaleDateString('en-US', {
        year: 'numeric',
        month: 'long',
        day: 'numeric',
      });
    };

    const CLASS_NAMES = {
      'AKIEC': 'Actinic Keratosis / Intraepidermal Carcinoma',
      'BCC': 'Basal Cell Carcinoma',
      'BEN_OTH': 'Other Benign Proliferations',
      'BKL': 'Benign Keratinocytic Lesion',
      'DF': 'Dermatofibroma',
      'INF': 'Inflammatory Conditions',
      'MAL_OTH': 'Other Malignant Proliferations',
      'MEL': 'Melanoma',
      'NV': 'Melanocytic Nevus',
      'SCCKA': 'Squamous Cell Carcinoma / Keratoacanthoma',
      'VASC': 'Vascular Lesions',
    };

    const predictions = caseData.details?.all_predictions || [];

    const html = `
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <style>
        * { margin: 0; padding: 0; }
        body { font-family: Arial, sans-serif; color: #333; line-height: 1.6; }
        .page { page-break-after: always; padding: 40px; }
        .header { 
            border-bottom: 3px solid #2563eb; 
            margin-bottom: 30px; 
            padding-bottom: 20px;
        }
        .title { 
            font-size: 28px; 
            font-weight: bold; 
            color: #1e40af;
            margin-bottom: 10px;
        }
        .subtitle { font-size: 14px; color: #666; }
        .section { margin-bottom: 25px; }
        .section-title { 
            font-size: 14px; 
            font-weight: bold; 
            color: #1e40af;
            text-transform: uppercase;
            border-bottom: 2px solid #ddd;
            padding-bottom: 8px;
            margin-bottom: 15px;
        }
        .row { display: flex; margin-bottom: 12px; }
        .col { flex: 1; }
        .label { 
            font-weight: bold; 
            color: #666; 
            font-size: 12px;
            text-transform: uppercase;
        }
        .value { 
            font-size: 14px; 
            color: #333;
            margin-top: 4px;
        }
        .prediction-box {
            padding: 15px;
            border-left: 4px solid #2563eb;
            background-color: #f0f9ff;
            margin-bottom: 12px;
            border-radius: 4px;
        }
        .prediction-main { font-size: 18px; font-weight: bold; color: #1e40af; }
        .prediction-conf { font-size: 14px; color: #666; margin-top: 5px; }
        .table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        .table th, .table td { 
            padding: 10px; 
            text-align: left; 
            border-bottom: 1px solid #ddd;
        }
        .table th { 
            background-color: #f3f4f6; 
            font-weight: bold;
            font-size: 12px;
        }
        .notes-box {
            background-color: #f9fafb;
            padding: 15px;
            border-radius: 4px;
            border: 1px solid #ddd;
            margin-top: 10px;
            font-size: 13px;
            white-space: pre-wrap;
            word-break: break-word;
        }
        .disclaimer {
            background-color: #fef3c7;
            border-left: 4px solid #f59e0b;
            padding: 15px;
            margin-top: 30px;
            border-radius: 4px;
            font-size: 11px;
        }
        .disclaimer-title { font-weight: bold; margin-bottom: 8px; }
        .footer {
            text-align: center;
            font-size: 11px;
            color: #999;
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #ddd;
        }
        .tags { display: flex; gap: 8px; flex-wrap: wrap; margin-top: 10px; }
        .tag { 
            background-color: #dbeafe; 
            color: #1e40af;
            padding: 4px 8px; 
            border-radius: 12px;
            font-size: 11px;
            font-weight: bold;
        }
    </style>
</head>
<body>
    <div class="page">
        <div class="header">
            <div class="title">${t.title}</div>
            <div class="subtitle">${formatDate(caseData.savedAt)}</div>
        </div>

        <!-- Case Information -->
        <div class="section">
            <div class="section-title">${t.patientId}</div>
            <div class="row">
                <div class="col">
                    <div class="label">${t.patientId}</div>
                    <div class="value">${caseData.patientId || 'Not specified'}</div>
                </div>
                <div class="col">
                    <div class="label">${t.caseId}</div>
                    <div class="value">${caseData.id ? caseData.id.substring(0, 12) : 'N/A'}...</div>
                </div>
                <div class="col">
                    <div class="label">${t.lesionLocation}</div>
                    <div class="value">${caseData.lesionLocation || 'Not specified'}</div>
                </div>
            </div>
        </div>

        <!-- AI Prediction -->
        <div class="section">
            <div class="section-title">${t.aiPrediction}</div>
            <div class="prediction-box">
                <div class="prediction-main">${CLASS_NAMES[caseData.aiPrediction] || caseData.aiPrediction}</div>
                <div class="prediction-conf">${t.confidence}: ${caseData.confidence?.toFixed(1) || 'N/A'}%</div>
            </div>
        </div>

        <!-- Doctor Assessment -->
        ${caseData.doctorOverride ? `
        <div class="section">
            <div class="section-title">${t.doctorAssessment}</div>
            <div class="prediction-box" style="border-left-color: #9333ea; background-color: #f3e8ff;">
                <div class="prediction-main" style="color: #6b21a8;">${CLASS_NAMES[caseData.doctorOverride] || caseData.doctorOverride}</div>
            </div>
        </div>
        ` : ''}

        <!-- Clinical Notes -->
        ${caseData.clinicalNotes ? `
        <div class="section">
            <div class="section-title">${t.clinicalNotes}</div>
            <div class="notes-box">${caseData.clinicalNotes}</div>
        </div>
        ` : ''}

        <!-- Follow-up and Tags -->
        <div class="section">
            ${caseData.followupDate ? `
            <div style="margin-bottom: 15px;">
                <div class="label">${t.followUp}</div>
                <div class="value">${formatDate(caseData.followupDate)}</div>
            </div>
            ` : ''}
            ${caseData.tags && caseData.tags.length > 0 ? `
            <div>
                <div class="label">${t.tags}</div>
                <div class="tags">
                    ${caseData.tags.map(tag => `<span class="tag">${tag}</span>`).join('')}
                </div>
            </div>
            ` : ''}
        </div>

        <!-- All Predictions Table -->
        ${predictions.length > 0 ? `
        <div class="section">
            <div class="section-title">${t.allClassPredictions}</div>
            <table class="table">
                <thead>
                    <tr>
                        <th>${t.class}</th>
                        <th>${t.probability}</th>
                    </tr>
                </thead>
                <tbody>
                    ${predictions.map(p => `
                        <tr>
                            <td>${CLASS_NAMES[p.class] || p.class}</td>
                            <td>${p.prob?.toFixed(2) || 'N/A'}%</td>
                        </tr>
                    `).join('')}
                </tbody>
            </table>
        </div>
        ` : ''}

        <!-- Disclaimer -->
        <div class="disclaimer">
            <div class="disclaimer-title">⚠️ ${t.disclaimer}</div>
            <div>${t.disclaimerText}</div>
        </div>

        <div class="footer">${t.footer}</div>
    </div>
</body>
</html>
    `;

    return html;
  }

  /**
   * Export HTML to PDF using browser's print functionality as fallback
   * or html2pdf if available
   */
  static async _exportToPDF(element, filename) {
    // Try using html2pdf library if available
    if (window.html2pdf) {
      const opt = {
        margin: 10,
        filename: filename,
        image: { type: 'jpeg', quality: 0.98 },
        html2canvas: { scale: 2 },
        jsPDF: { orientation: 'portrait', unit: 'mm', format: 'a4' },
      };
      window.html2pdf().set(opt).from(element).save();
    } else {
      // Fallback: Use print dialog
      const printWindow = window.open('', '', 'height=600,width=800');
      printWindow.document.write(`
        <html>
          <head>
            <title>${filename}</title>
            <style>
              ${element.style.cssText}
              body { margin: 20px; }
            </style>
          </head>
          <body>
            ${element.innerHTML}
          </body>
        </html>
      `);
      printWindow.document.close();
      printWindow.print();
    }
  }

  /**
   * Generate simple text export (for email, copy-paste)
   */
  static generateTextReport(caseData, language = 'en') {
    const formatDate = (dateString) => {
      return new Date(dateString).toLocaleDateString();
    };

    const CLASS_NAMES = {
      'AKIEC': 'Actinic Keratosis / Intraepidermal Carcinoma',
      'BCC': 'Basal Cell Carcinoma',
      'BEN_OTH': 'Other Benign Proliferations',
      'BKL': 'Benign Keratinocytic Lesion',
      'DF': 'Dermatofibroma',
      'INF': 'Inflammatory Conditions',
      'MAL_OTH': 'Other Malignant Proliferations',
      'MEL': 'Melanoma',
      'NV': 'Melanocytic Nevus',
      'SCCKA': 'Squamous Cell Carcinoma / Keratoacanthoma',
      'VASC': 'Vascular Lesions',
    };

    let text = `
═══════════════════════════════════════════════════════════════
SUDERM - CLINICAL CASE REPORT
═══════════════════════════════════════════════════════════════

Report Date: ${formatDate(caseData.savedAt)}

CASE INFORMATION
─────────────────────────────────────────────────────────────
Patient ID: ${caseData.patientId || 'Not specified'}
Case ID: ${caseData.id ? caseData.id.substring(0, 20) : 'N/A'}
Lesion Location: ${caseData.lesionLocation || 'Not specified'}

AI PREDICTION
─────────────────────────────────────────────────────────────
Classification: ${CLASS_NAMES[caseData.aiPrediction] || caseData.aiPrediction}
Confidence: ${caseData.confidence?.toFixed(1) || 'N/A'}%

${caseData.doctorOverride ? `
DOCTOR ASSESSMENT
─────────────────────────────────────────────────────────────
Assessment: ${CLASS_NAMES[caseData.doctorOverride] || caseData.doctorOverride}
` : ''}

${caseData.clinicalNotes ? `
CLINICAL NOTES
─────────────────────────────────────────────────────────────
${caseData.clinicalNotes}
` : ''}

${caseData.followupDate ? `
FOLLOW-UP
─────────────────────────────────────────────────────────────
Scheduled: ${formatDate(caseData.followupDate)}
` : ''}

${caseData.tags && caseData.tags.length > 0 ? `
TAGS
─────────────────────────────────────────────────────────────
${caseData.tags.join(', ')}
` : ''}

MEDICAL DISCLAIMER
═══════════════════════════════════════════════════════════════
This report is generated by an AI diagnostic tool and should 
not be considered a definitive diagnosis. All findings must 
be reviewed and confirmed by a qualified medical professional.

═══════════════════════════════════════════════════════════════
Generated by SUDerm - Skin Lesion Analysis System
    `.trim();

    return text;
  }
}

export default PDFExportService;
